// ANN inference starter
#include "ann_infer.h"

#include <string.h>

// Generated by X-CUBE-AI
#include "network.h"
#include "network_data.h"

#define ANN_IN_SCALE      (0.003801456f)
#define ANN_IN_ZERO       (-128)
#define ANN_OUT_SCALE     (0.00390625f)
#define ANN_OUT_ZERO      (-128)
#define ANN_ANGLE_MIN_DEG (-67.43497467041016f)
#define ANN_ANGLE_MAX_DEG (129.13128662109375f)

static ai_handle g_network = AI_HANDLE_NULL;
static ai_u8 g_activations[AI_NETWORK_DATA_ACTIVATIONS_SIZE];
static ai_i8 g_in_data[AI_NETWORK_IN_1_SIZE_BYTES];
static ai_i8 g_out_data[AI_NETWORK_OUT_1_SIZE_BYTES];

void ann_init(void) {
    ai_handle activations[] = { g_activations };
    ai_handle weights[] = { ai_network_data_weights_get() };
    ai_error err = ai_network_create_and_init(&g_network, activations, weights);
    if (err.type != AI_ERROR_NONE) {
        g_network = AI_HANDLE_NULL;
    }
}

static ai_i8 quantize_input(float v) {
    int q = (int)(v / ANN_IN_SCALE) + ANN_IN_ZERO;
    if (q < -128) q = -128;
    if (q > 127) q = 127;
    return (ai_i8)q;
}

static float normalize_angle(float angle_deg) {
    float denom = ANN_ANGLE_MAX_DEG - ANN_ANGLE_MIN_DEG;
    if (denom <= 0.0f) {
        return 0.0f;
    }
    float x = (angle_deg - ANN_ANGLE_MIN_DEG) / denom;
    if (x < 0.0f) x = 0.0f;
    if (x > 1.0f) x = 1.0f;
    return x;
}

static float denormalize_angle(float angle_norm) {
    float x = angle_norm;
    if (x < 0.0f) x = 0.0f;
    if (x > 1.0f) x = 1.0f;
    return ANN_ANGLE_MIN_DEG + x * (ANN_ANGLE_MAX_DEG - ANN_ANGLE_MIN_DEG);
}

static float ann_predict_run(const float *features,
                             size_t channels,
                             size_t samples,
                             const float *angle_history,
                             size_t history_samples,
                             float angle_value) {
    if (!g_network || !features) return 0.0f;

    // Expect 1x200x3 int8 input from report (size 600 bytes).
    // Layout: timesteps x 3 channels (EMG1, EMG2, angle history).
    const size_t input_steps = AI_NETWORK_IN_1_HEIGHT;
    const size_t input_ch = 3;
    if (samples != input_steps || channels != 2) {
        return 0.0f;
    }

    for (size_t t = 0; t < input_steps; t++) {
        g_in_data[t * input_ch + 0] = quantize_input(features[0 * samples + t]);
        g_in_data[t * input_ch + 1] = quantize_input(features[1 * samples + t]);
        float angle_src = angle_value;
        if (angle_history && history_samples == input_steps) {
            angle_src = angle_history[t];
        }
        float angle_norm = normalize_angle(angle_src);
        g_in_data[t * input_ch + 2] = quantize_input(angle_norm);
    }

    ai_buffer ai_input = AI_BUFFER_INIT(
        AI_FLAG_NONE,
        AI_NETWORK_IN_1_FORMAT,
        AI_BUFFER_SHAPE_INIT(AI_SHAPE_BCWH, 4, 1, AI_NETWORK_IN_1_CHANNEL, 1, AI_NETWORK_IN_1_HEIGHT),
        AI_NETWORK_IN_1_SIZE,
        NULL,
        g_in_data);

    ai_buffer ai_output = AI_BUFFER_INIT(
        AI_FLAG_NONE,
        AI_NETWORK_OUT_1_FORMAT,
        AI_BUFFER_SHAPE_INIT(AI_SHAPE_BCWH, 4, 1, AI_NETWORK_OUT_1_CHANNEL, 1, 1),
        AI_NETWORK_OUT_1_SIZE,
        NULL,
        g_out_data);

    if (ai_network_run(g_network, &ai_input, &ai_output) != 1) {
        return 0.0f;
    }

    ai_i8 q = g_out_data[0];
    float y = (float)(q - ANN_OUT_ZERO) * ANN_OUT_SCALE;
    float angle_deg = denormalize_angle(y);
    return angle_deg;
}

float ann_predict(const float *features, size_t channels, size_t samples, float angle_value) {
    return ann_predict_run(features, channels, samples, NULL, 0u, angle_value);
}

float ann_predict_with_history(const float *features,
                               size_t channels,
                               size_t samples,
                               const float *angle_history,
                               size_t history_samples) {
    return ann_predict_run(features, channels, samples, angle_history, history_samples, 0.0f);
}
